// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const section: string;
export const main_container: string;
export const header: string;
export const title: string;
export const subtitle: string;
export const form: string;
export const contact_icon: string;
export const email: string;
export const main_contact_container: string;
export const send_message_container: string;
export const send_button: string;
export const error_message: string;
export const message_sent: string;
