// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const filter_container: string;
export const project_container: string;
export const filter_by: string;
export const filter_options_container: string;
