// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const section: string;
export const skills_container: string;
export const code_background: string;
export const code_background_img: string;
export const code_background_overlay: string;
