// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const button: string;
export const button_alt: string;
export const title: string;
export const status: string;
export const skill: string;
export const skill_alt: string;
export const content: string;
export const content_alt: string;
export const skills_container: string;
export const datespan: string;
export const mobile_wrapper: string;
export const mobile_title: string;
export const mobile_expanded_indicator: string;
export const experience_container: string;
