// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const project_container: string;
export const project_carousel: string;
export const carousel_btn: string;
export const carousel_btn_right: string;
