// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const navbar: string;
export const navbar_links_container: string;
export const navbar_alt: string;
export const link: string;
export const active_link: string;
export const alt_link: string;
export const unfocused_link: string;
