// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const navmenu: string;
export const top_bar: string;
export const link_list: string;
export const navmenuclosebtn: string;
export const navmenulink: string;
export const active: string;
export const credits_container: string;
