// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const projectcard: string;
export const projectcard_tags_container: string;
export const projectcard_tag: string;
export const projectcard_image: string;
export const projectcard_title_container: string;
export const projectcard_title: string;
export const projectcard_category: string;
