// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const content: string;
export const project_details_container: string;
export const project_info_container: string;
export const project_view_container: string;
export const invalid_link: string;
export const backbutton: string;
export const project_header: string;
export const project_category: string;
export const project_title: string;
export const project_description: string;
export const project_gallery: string;
export const gallery_image: string;
export const project_view_title: string;
export const project_view_button: string;
